### ISSUE TITLE
StepToJsonParser is not a constructor error

### ISSUE THREAD

**Issue by tt2-dev** [aljoshakoecher/STEP-to-JSON#6] opened 2020-02-13 14:02 UTC
Hello,

first i wanna say thanks for this packet.
I am new on node.js. Why am i getting "StepToJsonParser is not a constructor" error when run the code below.

Can you help me please?

`const fs = require('fs');
const StepToJsonParser = require('step-to-json');

// To get your STEP-file's assembly structure as JSON:
const filePath = "test.step"
const stepFile = fs.readFileSync(filePath);
const parser = new StepToJsonParser(stepFile);

const assemblyStructure = parser.parse();`

**Comment by aljoshakoecher** [comment] 2020-02-13 14:32
Hi
Im actually amazed that there's already someone using this 😄 . The problem is, I fixed some things yesterday and didn't find the time to update the documentation. I will do that right now.

BTT: You have to slightly change your import. It has to be:
```javascript
const StepToJsonParser = require('step-to-json').StepToJsonParser;
```

The last part is what's missing in the documentation...

**Comment by aljoshakoecher** [comment] 2020-02-13 14:45
You can let me know if it works for you.
There is another thing I realized just today: STEP-Files can differ in the way they describe products and relations of products. This parser currently only works, if products are defined in PRODUCT_DEFINITION and relations as NEXT_ASSEMBLY_USAGE_OCCURRENCE. So depending on your STEP-file, you might not be getting the assembly structure...
I'm going to create a seperate issue for this.

**Comment by tt2-dev** [comment] 2020-02-13 14:46
Hi,

Thanks you for your quick reply :) I have updated my code too. 
But now i am getting another error as below.

"Error: Root component could not be found."

Is my step file caused this error?

**Comment by aljoshakoecher** [comment] 2020-02-13 15:01
I just created another issue describing the problem. But this is something else.
Your STEP-file contains an assembly?

**Comment by tt2-dev** [comment] 2020-02-13 15:31
Sorry but i have no idea about the step file :( I can add it here.

[test.step.zip](https://github.com/aljoshakoecher/STEP-to-JSON/files/4199161/test.step.zip)

**Comment by aljoshakoecher** [comment] 2020-02-13 16:01
I checked your file and I could open it in a CAD tool. The model looks like an assembly but the STEP file doesn't contain any assembly relations. That's why the parser couldn't find the root component.
You could try exporting your STEP file with different settings (e.g. using another AP) if that's possible. If not, then there's not much I can do. I'm closing this issue.

**Closed as completed by aljoshakoecher** 2020-02-13 16:01 UTC
Labels: needs documentation
